# Generated by Django 4.0.6 on 2022-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookitem_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='borrowed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
