# Generated by Django 4.0.6 on 2022-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookitem_borrowed_alter_bookitem_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='borrowed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
