# Generated by Django 4.0.6 on 2022-08-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookitem_borrowed_alter_bookitem_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='borrowed',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='dueDate',
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
