# Generated by Django 4.0.6 on 2022-08-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0002_alter_rack_library'),
        ('books', '0005_remove_bookitem_borrowed_remove_bookitem_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_sys.library'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='bookInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
