# Generated by Django 4.0.6 on 2022-08-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_sys.library'),
        ),
    ]
